#!/usr/bin/env python3
"""Office help cards: check labels, write HELP_CARDS into index.html, print PDF.
Run from anywhere:  python3 scripts/help-cards/build.py
Needs a Chromium for the PDF: set CHROME, else /opt/pw-browsers/... is tried;
without one the PDF step is skipped (the in-app help is still written)."""
import html, json, os, re, subprocess, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, HERE)
from cards import CARDS, SCREENS

APP = os.path.join(ROOT, 'index.html')
src = open(APP, encoding='utf-8').read()

# 1. every boxed label must exist in the app, exactly
srcu = html.unescape(src)
bad = [(c['id'], lab) for c in CARDS for t in c['steps'] + c.get('watch', []) + [c['done'], c['when']]
       for lab in re.findall(r'\[\[(.+?)\]\]', t) if lab not in src and lab not in srcu]
if bad:
    sys.exit('Labels not found in index.html: ' + repr(bad))

# 2. HELP_CARDS into index.html between the markers
data = [dict(id=c['id'], group=c['group'], title=c['title'], when=c['when'], steps=c['steps'],
             done=c['done'], watch=c.get('watch', []), screens=SCREENS.get(c['id'], [])) for c in CARDS]
js = 'const HELP_CARDS = ' + json.dumps(data, ensure_ascii=False, indent=0).replace('</', '<\\/') + ';'
a, b = '// HELP_CARDS:BEGIN (generated by scripts/help-cards/build.py; edit cards.py, not this)', '// HELP_CARDS:END'
if a not in src or b not in src:
    sys.exit('HELP_CARDS markers not found in index.html')
i, j = src.index(a) + len(a), src.index(b)
new = src[:i] + '\n    ' + js + '\n    ' + src[j:]
if new != src:
    open(APP, 'w', encoding='utf-8').write(new)
print(len(CARDS), 'cards checked and written to index.html')

# 3. the printable PDF
def fmt(t):
    t = html.escape(t)
    return re.sub(r'\[\[(.+?)\]\]', lambda m: f'<span class="btn">{m.group(1)}</span>', t)
groups = []
for c in CARDS:
    if c['group'] not in groups: groups.append(c['group'])
css = '''
@page { size: 5.5in 8.5in; margin: 0.35in 0.4in 0.4in; }
* { box-sizing: border-box; }
body { font-family: "Helvetica Neue", Arial, sans-serif; color: #1d1d1f; margin: 0; font-size: 11.5pt; line-height: 1.35; }
.card { page-break-after: always; break-after: page; display: flex; flex-direction: column; min-height: 7.7in; }
.card:last-child { page-break-after: auto; }
.top { display: flex; justify-content: space-between; align-items: baseline; border-bottom: 2.5px solid #1d1d1f; padding-bottom: 4px; }
.grp { font-size: 8.5pt; text-transform: uppercase; letter-spacing: .08em; color: #555; font-weight: 700; }
.id { font-size: 10pt; font-weight: 800; background: #1d1d1f; color: #fff; padding: 1px 7px; border-radius: 4px; }
h1 { font-size: 19pt; margin: 8px 0 2px; line-height: 1.15; }
.when { color: #444; font-size: 10.5pt; margin: 0 0 8px; }
.when b { color: #1d1d1f; }
ol { margin: 0 0 8px 0; padding-left: 0; list-style: none; counter-reset: s; }
ol li { counter-increment: s; position: relative; padding: 4px 0 4px 30px; border-bottom: 1px solid #e6e6e6; }
ol li::before { content: counter(s); position: absolute; left: 0; top: 4px; width: 21px; height: 21px; border-radius: 50%;
  background: #2d4373; color: #fff; font-weight: 800; font-size: 10pt; text-align: center; line-height: 21px; }
.btn { display: inline-block; font-weight: 700; border: 1.3px solid #2d4373; color: #2d4373; border-radius: 4px; padding: 0 4px; line-height: 1.3; white-space: nowrap; }
.box { border-radius: 6px; padding: 6px 9px; margin-top: 6px; font-size: 10.5pt; }
.box h3 { margin: 0 0 2px; font-size: 9pt; text-transform: uppercase; letter-spacing: .06em; }
.done { background: #e8f3ea; border-left: 5px solid #1b7a34; }
.done h3 { color: #1b7a34; }
.watch { background: #fdf3e1; border-left: 5px solid #b26a00; }
.watch h3 { color: #8a5200; }
.watch ul { margin: 0; padding-left: 16px; }
.watch li { margin: 2px 0; }
.foot { margin-top: auto; font-size: 7.5pt; color: #888; display: flex; justify-content: space-between; border-top: 1px solid #ddd; padding-top: 3px; }
.cover h1 { font-size: 22pt; }
.toccols { column-count: 2; column-gap: 14px; }
.toc { width: 100%; border-collapse: collapse; font-size: 8.8pt; break-inside: avoid; margin-bottom: 4px; }
.toc td { padding: 1.5px 3px; border-bottom: 1px solid #eee; vertical-align: top; }
.toc td.i { font-weight: 800; width: 26px; }
.toc tr.g td { font-weight: 700; text-transform: uppercase; font-size: 7.5pt; letter-spacing: .06em; color: #555; padding-top: 4px; border-bottom: 1.5px solid #1d1d1f; }
.key { margin-top: 10px; font-size: 10pt; color: #333; }
'''

out=[f'<!doctype html><html><head><meta charset="utf-8"><title>JFR Office Task Cards</title><style>{css}</style></head><body>']
# cover
rows=[]
for g in groups:
    t=[f'<tr class="g"><td colspan="2">{html.escape(g)}</td></tr>']
    for c in CARDS:
        if c['group']==g: t.append(f'<tr><td class="i">{c["id"]}</td><td>{html.escape(c["title"])}</td></tr>')
    rows.append('<table class="toc">'+''.join(t)+'</table>')
out.append(f'''<div class="card cover"><div class="top"><span class="grp">JFR Ranch Co. · Cattle Office app</span><span class="id">Office</span></div>
<h1>Office task cards</h1><p class="when">One card per job, for Jimmy and Lauren. Follow the steps in order.</p>
<div class="toccols">{''.join(rows)}</div>
<p class="key">A word in a box, like <span class="btn">Save</span>, is the button or field to tap, written exactly as it shows on the screen.
<b>Done when</b> says what proves it saved. <b>Watch for</b> lists the checks that protect the books: read them, never skip them.</p>
<div class="foot"><span>DRAFT · 3 Oct 2026 · check against the screen before laminating</span><span>Cover</span></div></div>''')
for c in CARDS:
    steps=''.join(f'<li>{fmt(s)}</li>' for s in c['steps'])
    watch=''.join(f'<li>{fmt(w)}</li>' for w in c.get('watch',[]))
    out.append(f'''<div class="card"><div class="top"><span class="grp">{html.escape(c["group"])}</span><span class="id">{c["id"]}</span></div>
<h1>{html.escape(c["title"])}</h1><p class="when"><b>When:</b> {fmt(c["when"])}</p>
<ol>{steps}</ol>
<div class="box done"><h3>Done when</h3>{fmt(c["done"])}</div>
{f'<div class="box watch"><h3>Watch for</h3><ul>{watch}</ul></div>' if watch else ''}
<div class="foot"><span>DRAFT · 3 Oct 2026</span><span>{c["id"]} · {html.escape(c["title"])}</span></div></div>''')
out.append('</body></html>')
page = os.path.join('/tmp', 'office-task-cards.html')
open(page, 'w', encoding='utf-8').write('\n'.join(out))
chrome = os.environ.get('CHROME') or '/opt/pw-browsers/chromium-1194/chrome-linux/chrome'
if os.path.exists(chrome):
    subprocess.run([chrome, '--headless', '--no-sandbox', '--disable-gpu', '--no-pdf-header-footer',
                    '--print-to-pdf=/tmp/office-task-cards.pdf', page], stderr=subprocess.DEVNULL, check=False)
    print('PDF: /tmp/office-task-cards.pdf')
else:
    print('No Chromium found; PDF skipped (HTML at ' + page + ')')
