# Office task cards: the ONE source for the in-app help dock and the printed
# PDF. [[Label]] = exact on-screen text (a boxed button or field).
#   python3 scripts/help-cards/build.py   -> checks every [[Label]] exists in
#   index.html, writes HELP_CARDS into index.html between the HELP_CARDS
#   markers, and prints the PDF to /tmp/office-task-cards.pdf.
# SCREENS says which screen(s) each card belongs to (a view id, 'appr:<pane>'
# or 'lot:<lot sub-tab>'); the dock opens the card for the screen in view.
CARDS = [
# ---------------- DAILY ----------------
dict(id="A1", group="Every morning", title="Approve field entries",
 when="Every morning, after the crew's phones have synced.",
 steps=[
  "Tap [[Approvals]] at the top. The [[Field entries]] list opens. The red numbers update when you come back to the app; [[Refresh]] reloads everything.",
  "Look at the top of the list. Rows under [[Needs info]] cannot be approved yet. Fix them with the pencil (see card A2) or send them back.",
  "Check each day's rows: tag, action, medicine, date.",
  "Tick the rows that are right, or tap [[Select all]] for a whole day.",
  "Tap [[Approve selected]].",
  "Read the box that pops up (how many doctorings, deaths, moves). Tap OK.",
 ],
 done="Green message: “N entries posted to the books.” The rows leave the list.",
 watch=[
  "If the pop-up says a medicine is unpriced, tap Cancel and tell John. It would post at $0 and cannot be fixed later.",
  "A death posts with no cause. Fill the cause in later on the lot (⚠ + Record deaths → tap the death).",
  "If it says “rolled back — nothing was posted”, nothing changed. Read the reason and fix that row.",
 ]),
dict(id="A2", group="Every morning", title="Fix or send back a field entry",
 when="A field entry is wrong, or sits under Needs info.",
 steps=[
  "In [[Approvals]] → [[Field entries]], find the row.",
  "Wrong date only: tap the date box on the row and pick the right day. It saves by itself.",
  "Wrong pasture, lot, tag, medicine or head: tap the pencil [[✎]] on the row, fix it, tap [[Save correction]].",
  "Cannot fix it (cowboy must redo it): tap [[✖ Send back]], type why, tap OK. The cowboy sees your reason.",
 ],
 done="“Correction saved.”, “Moved to (date).” or “Entry rejected and sent back.” The row shows “edited” after a correction.",
 watch=[
  "A red message saying nothing was changed means someone else already approved or rejected it. Refresh the list.",
  "A pasture count that does not match the books cannot be approved. A death, sale or move is missing. Find it first.",
 ]),
dict(id="A3", group="Every morning", title="Approve the PB feed report",
 when="Every morning, once the PB report has come in.",
 steps=[
  "Tap [[Approvals]] → [[Feed]].",
  "Each waiting day is a card. Check the pens: “PB pen → our pasture”, pounds fed.",
  "Any red problem must be fixed first (card A4). [[Approve & post]] stays grey until then.",
  "Check the line under “Charges to”. It should say the pounds tie.",
  "Tap [[Approve & post]].",
 ],
 done="Green message: “(date) approved and posted to the lots.” The day shrinks to one line with your name and the time.",
 watch=[
  "There is no OK box. One tap posts the feed to the lots. Only John can undo it.",
  "“No PB report for (dates)” means a day is missing. Tell John.",
  "Use [[PB email]] to open the original email if numbers look wrong.",
 ]),
dict(id="A4", group="Every morning", title="Fix a pen on the PB feed report",
 when="A PB pen went to a different pasture, to two pastures, to a pen waiting for cattle, or to the cows.",
 steps=[
  "In [[Approvals]] → [[Feed]], find the pen row on the day's card.",
  "Went to one other pasture: tap [[Move]], pick the pasture, tap [[Move]] in the box.",
  "Went to two or more pastures: tap [[Split]]. Pick each pasture and type its pounds. Use [[+ Pasture]] for more. When the line shows ✓, tap [[Save split]].",
  "Feed went into an empty pen before cattle arrive: tap [[Prefeed]]. The first lot to move in pays. Tap [[Undo prefeed]] to take it back.",
  "Feed went to the cows (not a lot): tap [[Cost centre]], pick it, tap [[Charge to cost centre]].",
  "Then approve the day (card A3).",
 ],
 done="The pen shows “(moved for this day)”, “split”, “Prefeed - first lot in pays” or the cost centre tag.",
 watch=[
  "Each fix is for that one day only.",
  "A split must add up exactly to PB's pounds for the pen.",
  "Whole day wrong? Tap [[Reject]], type why, tap [[Reject day]].",
 ]),
dict(id="A5", group="Every morning", title="Post a Bar J medicine invoice",
 when="Approvals shows a number on Meds.",
 steps=[
  "Tap [[Approvals]] → [[Meds]].",
  "On the invoice card, tap [[Review & post]]. The purchase screen opens, filled in.",
  "Pick [[Received to]] (where the medicine went). Required.",
  "Any line without a medicine: pick it. Brand-new medicine: tap [[New medication]].",
  "Check the tie line says “ties”.",
  "Tap [[Post purchase]].",
 ],
 done="“Purchase posted: N line(s), $X.” The invoice moves to “Recently posted or rejected”.",
 watch=[
  "It will not post until the lines add up to the invoice total (within 2¢).",
  "Not ours, or wrong? Tap [[Reject]] on the card and type why.",
 ]),
# ---------------- CATTLE IN ----------------
dict(id="B1", group="Cattle coming in", title="Start a new lot",
 when="A new set of cattle is bought.",
 steps=[
  "On [[Lots]], tap [[+ New lot]].",
  "Type the [[Lot number]].",
  "Check the [[Arrival date]] (today is filled in).",
  "Type the [[Estimated purchase weight]] per head. Required.",
  "Fill source, sex/class and notes if you have them.",
  "Tap [[Save lot]].",
 ],
 done="“Lot … created.” The lot opens on its Purchases tab, ready for the invoice and load out.",
 watch=[]),
dict(id="B2", group="Cattle coming in", title="Enter the purchase invoice",
 when="The bill for the cattle arrives.",
 steps=[
  "Open the lot (tap it on [[Lots]]). Tap the [[Purchases]] tab. A lot you just made is already there.",
  "Tap [[📄 + Invoice]].",
  "Fill [[Invoice date]], [[Head count]], [[Total weight (lbs)]] and [[Total cost ($)]]. All required.",
  "Check the [[Receiving protocol]]. It is picked for you from the lot (or the only Receiving protocol).",
  "Tap [[Save invoice]].",
  "To tie the invoice to its load outs: tap the invoice again, tick the load outs under [[Reconcile load outs]], tap [[Save invoice]].",
 ],
 done="“Invoice saved.” It shows in the Invoices card.",
 watch=[
  "“DUPLICATE INVOICE — not saved” means this invoice is already in. Open the one that is there.",
  "“None (no processing cost)” means no processing cost is charged. Only pick it on purpose.",
 ]),
dict(id="B3", group="Cattle coming in", title="Enter a load out (cattle delivered)",
 when="A truck of cattle is unloaded.",
 steps=[
  "Open the lot → [[Purchases]] tab → [[🚛 + Load Out]].",
  "Check the [[Load out date]]. Type the [[Head count]].",
  "Type [[Start tag]] and [[End tag]]. List any gaps in [[Missing tags]].",
  "Pick the ranch, then the pasture they went into. Split across pastures with [[+ Add pasture]].",
  "Check the [[Receiving protocol]] (picked for you from the lot).",
  "Tap [[Save load out]].",
 ],
 done="Green message: “Load out saved: N head in, N tag(s) registered.”",
 watch=[
  "Tag count must equal head count.",
  "“DUPLICATE LOAD OUT — not saved” means it is already in. Do not enter it twice.",
  "If tags belong to another lot, a box opens. [[Skip conflicting tags]] or [[Register anyway]] (needs a reason). Ask John if unsure.",
  "After saving, only protocol, invoice and notes can change. Wrong head, tags, date or pasture: delete the load out and enter it again.",
 ]),
dict(id="B4", group="Cattle coming in", title="Print the receiving sheet",
 when="Before the crew works new cattle.",
 steps=[
  "Tap your name (top right) → [[Settings]]. The Protocols list opens.",
  "Tap the protocol.",
  "Tap [[🖨 Receiving Sheet]].",
  "Type the average weight of the cattle.",
  "Tap [[🖨 Print]], or [[📱 Text PDF]] to send it to a phone.",
 ],
 done="The print window opens.",
 watch=["Write lot, date and head on the sheet by hand."]),
# ---------------- HEALTH ----------------
dict(id="C1", group="Health", title="Enter doctoring from a paper list",
 when="Several head got the same treatment and it was not entered in the field app.",
 steps=[
  "Tap [[Health]] → [[Doctoring Entry (bulk)]].",
  "Check the [[Date]].",
  "Pick the action under Action / protocol. The tag box opens.",
  "Type a tag and press Enter. Repeat for every head.",
  "Check each row's pasture and doses.",
  "Tap [[Save batch]].",
 ],
 done="Green message: “Saved N doctoring event(s).”",
 watch=[
  "Deaths are not entered here. Use ⚠ + Record deaths (card C3).",
  "A tag that is dead, sold or not on an open lot is refused.",
  "Changing the action clears the rows. [[Clear batch]] empties the list.",
 ]),
dict(id="C2", group="Health", title="Enter one doctoring",
 when="One animal was treated.",
 steps=[
  "Tap [[Health]] → [[Single Doctoring]].",
  "In the tag box, type the tag and press Enter. The entry opens on the right lot.",
  "No tag: tick [[NT animal (no tag)]], pick the lot, tap [[Open entry]].",
  "Pick the action. Check medicine and doses.",
  "Tap [[Save]].",
 ],
 done="“Saved. Ready for the next tag.” (“Closed without saving.” means it did not save.)",
 watch=["Deaths go on ⚠ + Record deaths, not here."]),
dict(id="C3", group="Health", title="Record a death",
 when="An animal dies.",
 steps=[
  "Open the lot → [[Animal Health]] tab.",
  "Tap [[⚠ + Record deaths]].",
  "Check the [[Date]]. Type the cause if known.",
  "Type the [[Tag #]]. Pick the pasture it died in. Head is 1.",
  "More than one? Tap [[+ Add row]].",
  "Tap [[Save]].",
 ],
 done="Green message: “Recorded N death event(s).” The tag is retired.",
 watch=[
  "Only John can delete a death. If one is wrong, tell him.",
  "If the lot reaches 0 head the app asks to close the lot.",
 ]),
dict(id="C4", group="Health", title="Write off missing, or a stray came back",
 when="Head are gone with no carcass, or a lost head turned up.",
 steps=[
  "Open the lot → [[Animal Health]] tab.",
  "Tap [[− Write off missing]] or [[+ Stray returned]].",
  "Check the [[Date]]. Type the [[Head]].",
  "Pick the pasture. Check it is the right one.",
  "Tap [[Save]].",
 ],
 done="Green message saying how many head were written off or added back.",
 watch=["Missing is not a death. Only John can reverse one."]),
dict(id="C5", group="Health", title="Send cattle to the feed pen",
 when="Sick or poor-doing head go to the feed pen.",
 steps=[
  "Open the lot → [[Moves]] tab.",
  "Tap [[🩹 Send to feed pen]].",
  "On the line: pick the pasture they came from, type the head, pick the pen they went to.",
  "Tap [[Save transfer]].",
 ],
 done="Green message: “Sent to the feed pen.”",
 watch=["Check the “to” pasture. It starts on the pasture they left."]),
dict(id="C6", group="Health", title="Feed pen: sold, butchered, died or gone",
 when="A head leaves the feed pen.",
 steps=[
  "Open the feed pen lot → [[Feed pen]] tab.",
  "Tap [[+ Record removal]].",
  "Pick what happened. Check the date and pen.",
  "Sold: type the proceeds. Type how many head.",
  "Tap [[Save removal]].",
 ],
 done="Green message: “Removal recorded (Sold).” (or Butchered, Died, Disappeared)",
 watch=["Sold or butchered shows the withdrawal warning if any tag is still in withdrawal. Read the tags before you confirm."]),
# ---------------- CATTLE MOVING / OUT ----------------
dict(id="D1", group="Moving and selling", title="Move cattle between pastures",
 when="Cattle were moved and it was not entered in the field app.",
 steps=[
  "Tap [[Moves & Sales]]. It opens on [[Moves]] (tap that sub-tab if it does not).",
  "On the ticket: pick the lot (the pasture they left fills in when the lot is in one pasture), type the head, pick the pasture they went to.",
  "More moves? Tap [[+ Move ticket]].",
  "Check the date on each ticket.",
  "Tap [[Save moves]], then OK.",
 ],
 done="Green message: “N move(s) recorded.”",
 watch=["If any one ticket fails, none are saved. Read the reason."]),
dict(id="D2", group="Moving and selling", title="Undo a wrong move",
 when="A move was entered by mistake.",
 steps=[
  "Open the lot → [[Moves]] tab → move history.",
  "On the wrong move, tap [[Reverse]]. Tap OK.",
 ],
 done="Green message: “Move reversed.” The old move shows “Reversed”; both stay in the history.",
 watch=["It refuses if the cattle have moved, died or sold since. Ask John."]),
dict(id="D3", group="Moving and selling", title="Ship cattle (sale)",
 when="Cattle are sold and shipped.",
 steps=[
  "Tap [[Moves & Sales]] → [[Shipments]] → [[+ New shipment]]. (From a lot, [[💲 + Sale]] opens the same screen with the lot filled in.)",
  "Set the [[Sale date]] first. Type the buyer.",
  "On each load: head, gross pounds, and the lot (its pasture fills in when the lot is in one pasture).",
  "Type the [[$ per cwt]] and any shrink. Check deductions.",
  "Wait for “Ready to save. Everything ties.”",
  "Tap [[Save shipment]], then OK.",
 ],
 done="Green message: “Shipment saved: N head … to the books.”",
 watch=[
  "A withdrawal box lists tags still in withdrawal. Make sure none are on the truck before [[Confirm — save anyway]].",
  "Only John can delete a shipment.",
 ]),
dict(id="D4", group="Moving and selling", title="Copy a shipment into Redwing",
 when="After a shipment is saved.",
 steps=[
  "Tap [[Moves & Sales]] → [[Accounting Report]] (or [[Accounting report]] on the shipment).",
  "Pick the shipment.",
  "Type the [[Production Year]]. It is decided for each sale.",
  "Check the banner says the rows tie.",
  "Tap [[Copy rows]] and paste into Redwing.",
 ],
 done="“N row(s) copied — paste into your accounting grid.”",
 watch=["A red banner means the rows do not tie. Do not post. Tell John."]),
dict(id="D5", group="Moving and selling", title="Check the head count",
 when="Every morning, and after any big day.",
 steps=[
  "On [[Lots]], look at the Head count tile at the top.",
  "Green = every lot ties. Red = at least one lot does not.",
  "Red: tap the tile. Lots marked OFF are at the top. Tap one to open it.",
 ],
 done="Nothing to save. Green is good.",
 watch=[
  "Books higher than pastures: some head have no pasture. Place them with ↔ + Move on the lot.",
  "Pastures higher than books: a death, sale or move was not entered. Find it, or tell John.",
 ]),
dict(id="D6", group="Moving and selling", title="Settle a pasture count",
 when="The crew counted a pasture and the lot split is off.",
 steps=[
  "Tap your name (top right) → [[Settings]] → [[Locations]] → the ranch → the pasture.",
  "Tap [[Settle counts]].",
  "Type the head counted for every lot (0 if none).",
  "For each lot that changed, pick the other pasture the head came from or went to.",
  "Tap [[Record the count]].",
 ],
 done="Green message: “(pasture) settled” or “verified against the count”.",
 watch=["The total counted must match the books. If not, a death, sale or move is missing."]),
# ---------------- FEED ----------------
dict(id="E1", group="Feed and medicine", title="Enter a feed delivery",
 when="A load of feed arrives.",
 steps=[
  "Tap [[Inventory]] → [[Purchases]] → [[+ Delivery]].",
  "If it was ordered, pick it under Against which order? (fills most of it).",
  "Check the date. Pick the item, where it went, and the vendor.",
  "Type the pounds (or amount) and the price, or tick [[Price not known yet]].",
  "Type the scale ticket number if you have it.",
  "Tap [[Save delivery]].",
 ],
 done="Green message: “Delivery recorded.”",
 watch=["Always pick the vendor, or the bill cannot be matched later."]),
dict(id="E2", group="Feed and medicine", title="Enter feed fed by hand",
 when="Feed went out that is not on the PB report.",
 steps=[
  "Tap [[Inventory]] → [[Feed Out]].",
  "Switch the mode to [[Single rows]] (first time only; it remembers).",
  "Check the period start and end.",
  "On each row: item, where it came out of, lot (or cost centre), [[Pounds fed]]. More rows with [[+ Row]].",
  "Tap [[Save feed-out]].",
 ],
 done="Green message: “Saved N feed-out row(s).”",
 watch=["An overlap warning means feed for that period is already in. Ask John before saving again."]),
dict(id="E3", group="Feed and medicine", title="Medicine checkout or return",
 when="A man takes medicine from the med room, or brings it back.",
 steps=[
  "Tap [[Inventory]] → [[Meds]] → [[Checkouts]].",
  "Pick who it goes to under [[Goes to]].",
  "Pick each medicine and the bottles.",
  "Tap [[Record checkout]] (or [[Record return]]).",
 ],
 done="“Checkout recorded …” or “Return recorded …”, and it shows in the log.",
 watch=["Picking another pool (not a man) moves the stock. The button then reads Move stock."]),
dict(id="E6", group="Feed and medicine", title="Charge medicine to a lot or a cost centre",
 when="Medicine went out with no doctoring record: a pour-on or water med on a whole lot, or medicine for the cows, bulls or horses.",
 steps=[
  "Tap [[Inventory]] → [[Meds]] → [[Charge out]].",
  "Check the date it was given, pick the medicine and the shelf, and type the quantity.",
  "Under [[Charge to]], pick a lot or a cost centre.",
  "A lot: pick the lot and the [[Closeout line]] (Processing, Treatment or Other). A cost centre: pick it from the list.",
  "Tap [[Post charge]].",
 ],
 done="“Charged … to lot … : $…” or “… to cost centre … : $…”, and it shows under Recent charges.",
 watch=["A withdrawal drug on a lot shows when the whole lot clears. It does not stop the charge.",
        "A cost centre with no Profit Center or Production Center says Coding missing. Ask John to fill it in.",
        "Wrong entry? Only John can Undo, and not once that month is counted."]),
dict(id="E4", group="Feed and medicine", title="Count the medicine",
 when="Monthly count.",
 steps=[
  "Tap [[Inventory]] → [[Meds]] → [[Counts]] → [[+ New count]].",
  "Type what is in the barn and with the crew for each medicine.",
  "Stop part way? Tap [[Save draft]] and come back later.",
  "When done, tap [[Post count]], then OK.",
 ],
 done="“Count posted: N counted, N short, N over.”",
 watch=["A blank line is skipped, not zero. Type 0 if none.", "A posted count cannot be changed. Only John can un-post."]),
dict(id="E5", group="Feed and medicine", title="Count a feed bay",
 when="A bay is due for a count (it shows on Needs Attention).",
 steps=[
  "Tap [[Inventory]]. On Needs Attention, tap the “Count overdue” row. (Or Settings ▾ → [[Counts]] → [[+ Count a bay]].)",
  "Check the date and location.",
  "Type what is there for each line. Empty bay: tick [[Bay is empty — zero every line]].",
  "Tap [[Post count]].",
 ],
 done="Green message: “Count posted. …”",
 watch=["If it asks about tons typed as pounds, check your numbers."]),
# ---------------- REPORTS ----------------
dict(id="F1", group="Reports", title="Send the daily report",
 when="End of the day.",
 steps=[
  "Tap [[Reports]] → [[Daily Report]].",
  "Use [[Today]] or the arrows to pick the day.",
  "Tap [[Text / share PDF]] to send it, [[Copy text]] to paste it, or [[Print]].",
 ],
 done="The share sheet or print window opens, or “Report copied …”.",
 watch=["[[Email]] only opens your mail app. You still pick who and tap Send."]),
]

SCREENS = {'A1': ['appr:field'], 'A2': ['appr:field'], 'A3': ['appr:feed'], 'A4': ['appr:feed'], 'A5': ['appr:meds', 'invMedPurchaseEntryView'], 'B1': ['lotsView'], 'B2': ['lot:purchases'], 'B3': ['lot:purchases'], 'B4': ['protocolsView', 'protocolDetailView'], 'C1': ['doctoringEntryView'], 'C2': ['doctoringSingleView'], 'C3': ['lot:health'], 'C4': ['lot:health'], 'C5': ['lot:moves'], 'C6': ['lot:feedpen'], 'D1': ['movesView'], 'D2': ['lot:moves'], 'D3': ['salesView', 'shipmentEntryView', 'lot:sales'], 'D4': ['salesReportView'], 'D5': ['lotsView'], 'D6': ['pastureDetailView', 'ranchDetailView', 'locationsView'], 'E1': ['invPurchasesView', 'feedReceiptsView'], 'E2': ['feedUsageView'], 'E3': ['invCheckoutsView'], 'E6': ['invChargeView'], 'E4': ['invCountsView', 'invCountEntryView'], 'E5': ['feedCountsView', 'invNeedsView'], 'F1': ['reportDailyView']}
